# Generated by Django 5.0.6 on 2025-08-05 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('game_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_gm', to=settings.AUTH_USER_MODEL)),
                ('jogadores', models.ManyToManyField(blank=True, related_name='salas_jogador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
