# Generated by Django 5.0.6 on 2025-08-09 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sala',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='salas_participando', to=settings.AUTH_USER_MODEL),
        ),
    ]
