# Generated by Django on 2025-08-17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_alter_sala_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='senha',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Senha (opcional)'),
        ),
    ]
