# Generated by Django 5.2.4 on 2025-12-30 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personagens', '0047_personagem_campanga'),
        ('salas', '0005_notasessao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Domínio')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ouro', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ouro')),
                ('populacao', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='População')),
                ('territorio', models.IntegerField(default=1, help_text='Número de territórios sob controle', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Territórios Controlados')),
                ('nivel_desenvolvimento', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nível de Desenvolvimento')),
                ('estabilidade', models.IntegerField(default=50, help_text='0-100, afeta produtividade e lealdade', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estabilidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('governante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dominios_governados', to='personagens.personagem', verbose_name='Governante')),
                ('jogadores_acesso', models.ManyToManyField(blank=True, related_name='dominios_acesso', to=settings.AUTH_USER_MODEL, verbose_name='Jogadores com Acesso')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
                'ordering': ['nome'],
            },
        ),
    ]
