# Generated by Django 5.2.4 on 2025-12-30 17:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='estabilidade',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='nivel_desenvolvimento',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='populacao',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='territorio',
        ),
        migrations.AddField(
            model_name='domain',
            name='brasao',
            field=models.ImageField(blank=True, null=True, upload_to='domains/brasoes/', verbose_name='Brasão'),
        ),
        migrations.AddField(
            model_name='domain',
            name='criado_por_gm',
            field=models.BooleanField(default=False, help_text='Se True, apenas o GM pode editar', verbose_name='Criado pelo GM'),
        ),
        migrations.AddField(
            model_name='domain',
            name='criador',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou este domínio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dominios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='domain',
            name='diplomacy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)], verbose_name='Diplomacy'),
        ),
        migrations.AddField(
            model_name='domain',
            name='dragonshards',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dragonshards'),
        ),
        migrations.AddField(
            model_name='domain',
            name='espionage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)], verbose_name='Espionage'),
        ),
        migrations.AddField(
            model_name='domain',
            name='establishment',
            field=models.IntegerField(default=0, help_text='Nível do Establishment (0 a 5, 0 = não possui)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Establishment'),
        ),
        migrations.AddField(
            model_name='domain',
            name='keep',
            field=models.IntegerField(default=0, help_text='Nível do Keep (0 a 5, 0 = não possui)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Keep'),
        ),
        migrations.AddField(
            model_name='domain',
            name='lore',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)], verbose_name='Lore'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nivel',
            field=models.IntegerField(default=1, help_text='Nível do domínio (1 a 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='domain',
            name='operations',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)], verbose_name='Operations'),
        ),
        migrations.AddField(
            model_name='domain',
            name='temple',
            field=models.IntegerField(default=0, help_text='Nível do Temple (0 a 5, 0 = não possui)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Temple'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tower',
            field=models.IntegerField(default=0, help_text='Nível da Tower (0 a 5, 0 = não possui)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Tower'),
        ),
    ]
