# Generated by Django 5.2.4 on 2025-12-30 19:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0002_remove_domain_estabilidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Infantaria Pesada, Arqueiros da Floresta, etc', max_length=200, verbose_name='Nome da Unidade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ataque', models.IntegerField(default=1, help_text='Capacidade de ataque da unidade', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ataque')),
                ('poder', models.IntegerField(default=1, help_text='Poder/Força da unidade', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Poder')),
                ('defesa', models.IntegerField(default=1, help_text='Capacidade defensiva da unidade', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Defesa')),
                ('resistencia', models.IntegerField(default=1, help_text='Resistência da unidade', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Resistência')),
                ('moral', models.IntegerField(default=1, help_text='Moral da unidade (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Moral')),
                ('custo_ouro', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo em Ouro')),
                ('custo_dragonshards', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo em Dragonshards')),
                ('quantidade', models.IntegerField(default=1, help_text='Número de soldados nesta unidade', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de Soldados')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criador', models.ForeignKey(help_text='Usuário que criou esta unidade', on_delete=django.db.models.deletion.CASCADE, related_name='units_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='domains_warfare.domain', verbose_name='Domínio')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['domain', 'nome'],
                'unique_together': {('domain', 'nome')},
            },
        ),
    ]
