# Generated by Django 5.2.4 on 2025-12-30 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0003_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAncestry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('bugbear', 'Bugbear'), ('dragonborn', 'Dragonborn'), ('dwarf', 'Dwarf'), ('elf', 'Elf'), ('elf_winged', 'Elf (Winged)'), ('ghoul', 'Ghoul'), ('gnoll', 'Gnoll'), ('gnome', 'Gnome'), ('goblin', 'Goblin'), ('hobgoblin', 'Hobgoblin'), ('human', 'Human'), ('kobold', 'Kobold'), ('lizardfolk', 'Lizardfolk'), ('ogre', 'Ogre'), ('orc', 'Orc'), ('skeleton', 'Skeleton'), ('treant', 'Treant'), ('troll', 'Troll'), ('zombie', 'Zombie')], max_length=50, unique=True, verbose_name='Ancestria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('modificador_ataque', models.IntegerField(default=0, verbose_name='Modificador de Ataque')),
                ('modificador_poder', models.IntegerField(default=0, verbose_name='Modificador de Poder')),
                ('modificador_defesa', models.IntegerField(default=0, verbose_name='Modificador de Defesa')),
                ('modificador_resistencia', models.IntegerField(default=0, verbose_name='Modificador de Resistência')),
                ('modificador_moral', models.IntegerField(default=0, verbose_name='Modificador de Moral')),
                ('traits', models.TextField(blank=True, help_text='Traits que esta ancestry automaticamente fornece (separados por vírgula)', verbose_name='Traits Associados')),
            ],
            options={
                'verbose_name': 'Ancestria de Unidade',
                'verbose_name_plural': 'Ancestrias de Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='ancestry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='domains_warfare.unitancestry', verbose_name='Ancestria'),
        ),
    ]
