# Generated by Django 5.2.4 on 2025-12-30 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0004_unitancestry_unit_ancestry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('amphibious', 'Amphibious'), ('bred_for_war', 'Bred for War'), ('brutal', 'Brutal'), ('courageous', 'Courageous'), ('eternal', 'Eternal'), ('feast', 'Feast'), ('horrify', 'Horrify'), ('martial', 'Martial'), ('mindless', 'Mindless'), ('regenerate', 'Regenerate'), ('ravenous', 'Ravenous'), ('rock_hurler', 'Rock-Hurler'), ('savage', 'Savage'), ('stalwart', 'Stalwart'), ('twisting_roots', 'Twisting Roots'), ('undead', 'Undead')], max_length=50, unique=True, verbose_name='Trait')),
                ('descricao', models.TextField(help_text='Explicação do que o trait faz', verbose_name='Descrição')),
                ('custo', models.IntegerField(default=0, help_text='Custo em pontos para adquirir este trait', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo')),
            ],
            options={
                'verbose_name': 'Trait de Unidade',
                'verbose_name_plural': 'Traits de Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='traits',
            field=models.ManyToManyField(blank=True, help_text='Traits que esta unidade adquiriu (além dos inatos da ancestry)', related_name='units', to='domains_warfare.unittrait', verbose_name='Traits Adquiridos'),
        ),
    ]
