# Generated by Django 5.2.4 on 2025-12-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0005_unittrait_unit_traits'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('green', 'Green'), ('regular', 'Regular'), ('seasoned', 'Seasoned'), ('veteran', 'Veteran'), ('elite', 'Elite'), ('super_elite', 'Super-Elite')], max_length=50, unique=True, verbose_name='Nível de Experiência')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('modificador_ataque', models.IntegerField(default=0, verbose_name='Modificador de Ataque')),
                ('modificador_poder', models.IntegerField(default=0, verbose_name='Modificador de Poder')),
                ('modificador_defesa', models.IntegerField(default=0, verbose_name='Modificador de Defesa')),
                ('modificador_resistencia', models.IntegerField(default=0, verbose_name='Modificador de Resistência')),
                ('modificador_moral', models.IntegerField(default=0, verbose_name='Modificador de Moral')),
            ],
            options={
                'verbose_name': 'Nível de Experiência de Unidade',
                'verbose_name_plural': 'Níveis de Experiência de Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='experience',
            field=models.ForeignKey(blank=True, help_text='Nível de experiência da unidade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='domains_warfare.unitexperience', verbose_name='Nível de Experiência'),
        ),
    ]
