# Generated by Django 5.2.9 on 2025-12-30 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0006_unitexperience_unit_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('super_heavy', 'Super-Heavy')], max_length=50, unique=True, verbose_name='Tipo de Equipamento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('modificador_poder', models.IntegerField(default=0, verbose_name='Modificador de Poder')),
                ('modificador_defesa', models.IntegerField(default=0, verbose_name='Modificador de Defesa')),
            ],
            options={
                'verbose_name': 'Tipo de Equipamento de Unidade',
                'verbose_name_plural': 'Tipos de Equipamento de Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Tipo de equipamento da unidade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='domains_warfare.unitequipment', verbose_name='Equipamento'),
        ),
    ]
