# Generated by Django 5.2.4 on 2025-12-30 20:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0007_unitequipment_unit_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('1d4', '1d4'), ('1d6', '1d6'), ('1d8', '1d8'), ('1d10', '1d10'), ('1d12', '1d12')], help_text='Tamanho da unidade em dados (1d4, 1d6, etc)', max_length=10, unique=True, verbose_name='Tamanho')),
                ('multiplicador_custo', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplica o custo final da unidade (ex: 1.33x, 0.66x)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='Multiplicador de Custo')),
            ],
            options={
                'verbose_name': 'Tamanho de Unidade',
                'verbose_name_plural': 'Tamanhos de Unidades',
                'ordering': ['tamanho'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('airborne', 'Airborne'), ('archers', 'Archers'), ('cavalry', 'Cavalry'), ('levies', 'Levies'), ('infantry', 'Infantry'), ('siege_engine', 'Siege Engine')], max_length=50, unique=True, verbose_name='Tipo de Unidade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('modificador_ataque', models.IntegerField(default=0, verbose_name='Modificador de Ataque')),
                ('modificador_poder', models.IntegerField(default=0, verbose_name='Modificador de Poder')),
                ('modificador_defesa', models.IntegerField(default=0, verbose_name='Modificador de Defesa')),
                ('modificador_resistencia', models.IntegerField(default=0, verbose_name='Modificador de Resistência (Toughness)')),
                ('modificador_moral', models.IntegerField(default=0, verbose_name='Modificador de Moral')),
                ('multiplicador_custo', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplica o custo final da unidade (ex: 1.5x, 0.75x)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='Multiplicador de Custo')),
            ],
            options={
                'verbose_name': 'Tipo de Unidade',
                'verbose_name_plural': 'Tipos de Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Tamanho da unidade (1d4, 1d6, etc)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='domains_warfare.unitsize', verbose_name='Tamanho da Unidade'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(blank=True, help_text='Tipo estratégico da unidade (Infantry, Cavalry, etc)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='domains_warfare.unittype', verbose_name='Tipo de Unidade'),
        ),
    ]
