# Generated by Django 5.2.4 on 2025-12-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0008_unitsize_unittype_unit_size_unit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem representativa da unidade', null=True, upload_to='units/', verbose_name='Imagem'),
        ),
    ]
