# Generated by Django 5.2.9 on 2025-12-31 18:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0009_unit_imagem'),
        ('salas', '0005_notasessao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CombateWarfare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Batalha de Lurching Tower, Cerco de Winterhold', max_length=200, verbose_name='Nome do Combate')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates_warfare_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates_warfare', to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Combate Warfare',
                'verbose_name_plural': 'Combates Warfare',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MapaWarfare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Mapa')),
                ('imagem', models.ImageField(upload_to='warfare/mapas/', verbose_name='Imagem do Mapa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Mapa Ativo')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas_warfare', to='domains_warfare.combatewarfare', verbose_name='Combate')),
            ],
            options={
                'verbose_name': 'Mapa Warfare',
                'verbose_name_plural': 'Mapas Warfare',
                'ordering': ['-adicionado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteWarfare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_iniciativa', models.IntegerField(default=0, help_text='Ordem no combate (menor = primeiro)', verbose_name='Ordem de Iniciativa')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='domains_warfare.combatewarfare', verbose_name='Combate')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_warfare', to='domains_warfare.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Participante Warfare',
                'verbose_name_plural': 'Participantes Warfare',
                'ordering': ['ordem_iniciativa', 'adicionado_em'],
                'unique_together': {('combate', 'domain')},
            },
        ),
        migrations.AddField(
            model_name='combatewarfare',
            name='domains',
            field=models.ManyToManyField(related_name='combates_warfare', through='domains_warfare.ParticipanteWarfare', to='domains_warfare.domain'),
        ),
        migrations.CreateModel(
            name='TurnoWarfare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=False, verbose_name='Turno Ativo')),
                ('tipo_acao', models.CharField(choices=[('ataque', 'Ataque'), ('movimento', 'Movimento'), ('esperar', 'Esperar'), ('outro', 'Outro')], default='ataque', max_length=50, verbose_name='Tipo de Ação')),
                ('roll_ataque', models.IntegerField(blank=True, null=True, verbose_name='Roll de Ataque (d20)')),
                ('roll_poder', models.IntegerField(blank=True, null=True, verbose_name='Roll de Poder (d20)')),
                ('roll_moral', models.IntegerField(blank=True, null=True, verbose_name='Roll de Moral (d20)')),
                ('sucesso_ataque', models.BooleanField(default=False, verbose_name='Ataque Bem-Sucedido')),
                ('sucesso_poder', models.BooleanField(default=False, verbose_name='Poder Bem-Sucedido')),
                ('falha_moral', models.BooleanField(default=False, verbose_name='Falha no Teste de Moral')),
                ('dano_causado', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dano Causado')),
                ('descricao', models.TextField(blank=True, help_text='Narrativa da ação', verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_warfare', to='domains_warfare.combatewarfare', verbose_name='Combate')),
                ('unit_alvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_alvo_warfare', to='domains_warfare.unit', verbose_name='Unidade Alvo')),
                ('unit_atacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_atacante_warfare', to='domains_warfare.unit', verbose_name='Unidade Atacante')),
            ],
            options={
                'verbose_name': 'Turno Warfare',
                'verbose_name_plural': 'Turnos Warfare',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PosicaoUnitWarfare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0, verbose_name='Posição X')),
                ('y', models.FloatField(default=0, verbose_name='Posição Y')),
                ('visivel', models.BooleanField(default=True, verbose_name='Visível')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_units', to='domains_warfare.mapawarfare', verbose_name='Mapa')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_warfare', to='domains_warfare.unit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Posição de Unidade Warfare',
                'verbose_name_plural': 'Posições de Unidades Warfare',
                'unique_together': {('mapa', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='StatusUnitWarfare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_atual', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='HP Atual')),
                ('hp_maximo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='HP Máximo')),
                ('diminished', models.BooleanField(default=False, help_text='Unit com ≤50% HP', verbose_name='Diminished')),
                ('incapacitado', models.BooleanField(default=False, help_text='Unit com 0 HP', verbose_name='Incapacitado')),
                ('efeitos_ativos', models.TextField(blank=True, help_text='JSON com efeitos temporários', verbose_name='Efeitos Ativos')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_units', to='domains_warfare.combatewarfare', verbose_name='Combate')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_warfare', to='domains_warfare.unit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Status de Unidade Warfare',
                'verbose_name_plural': 'Status de Unidades Warfare',
                'unique_together': {('combate', 'unit')},
            },
        ),
    ]
