# Generated by Django 5.2.4 on 2026-01-05 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0010_combatewarfare_mapawarfare_participantewarfare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatewarfare',
            name='hp_fortificacao_atual',
            field=models.IntegerField(blank=True, help_text='HP restante da fortificação durante o combate', null=True, verbose_name='HP Atual da Fortificação'),
        ),
        migrations.CreateModel(
            name='Fortificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('cerca_pedra', 'Cerca de Pedra'), ('torre_guarda', 'Torre de Guarda'), ('muros_cidade', 'Muros da Cidade'), ('portoes_cidade', 'Portões da Cidade'), ('torreao_keep', 'Torreão (Keep)'), ('castelo', 'Castelo')], max_length=100, verbose_name='Nome')),
                ('moral', models.IntegerField(default=0, help_text='Bônus adicionado ao roll de Moral (0-4)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Bônus de Moral')),
                ('defesa', models.IntegerField(default=0, help_text='Bônus adicionado à Defesa (0-4)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Bônus de Defesa')),
                ('poder', models.IntegerField(default=0, help_text='Bônus de Poder para Archers apenas (0-2)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Bônus de Poder')),
                ('hp_fortificacao', models.IntegerField(default=4, help_text='HP da própria fortificação (4-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Pontos de Vida da Fortificação')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da fortificação', verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Fortificação',
                'verbose_name_plural': 'Fortificações',
                'unique_together': {('nome',)},
            },
        ),
        migrations.AddField(
            model_name='combatewarfare',
            name='fortificacao',
            field=models.ForeignKey(blank=True, help_text='Fortificação presente neste combate (bônus para defensores)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combates_warfare', to='domains_warfare.fortificacao', verbose_name='Fortificação'),
        ),
    ]
