# Generated by Django 5.2.4 on 2026-01-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0011_combatewarfare_hp_fortificacao_atual_fortificacao_and_more'),
    ]

    operations = [
        # Noop - removing unique_together constraint creation
    ]

