# Generated by Django 5.2.4 on 2026-01-05 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0012_alter_fortificacao_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatewarfare',
            name='domain_defensor',
            field=models.ForeignKey(blank=True, help_text='Domain que está defendendo a fortificação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combates_defensores', to='domains_warfare.domain', verbose_name='Domain Defensor'),
        ),
    ]
