# Generated by Django 5.2.4 on 2026-01-05 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains_warfare', '0013_combatewarfare_domain_defensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_mythic',
            field=models.BooleanField(default=False, help_text='Se marcado, os atributos base podem ser definidos manualmente', verbose_name='Unidade Mítica'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ataque',
            field=models.IntegerField(default=0, help_text='Capacidade de ataque da unidade', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ataque'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='poder',
            field=models.IntegerField(default=0, help_text='Poder/Força da unidade', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poder'),
        ),
    ]
