# Generated by Django 5.0.6 on 2025-07-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dano', 'Dano'), ('aflicao', 'Aflição')], max_length=20)),
                ('alcance', models.CharField(choices=[('comum', 'Comum'), ('area', 'Área'), ('percepcao', 'Percepção')], max_length=20)),
                ('nivel', models.IntegerField()),
                ('defesa_usada', models.CharField(max_length=20)),
                ('acertou', models.BooleanField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques_recebidos', to='personagens.personagem')),
                ('atacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques_feitos', to='personagens.personagem')),
            ],
        ),
    ]
