# Generated by Django 5.0.6 on 2025-07-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0001_initial'),
        ('personagens', '0005_poder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciativa', models.IntegerField()),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combate.combate')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagens.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('ativo', models.BooleanField(default=False)),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combate.combate')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagens.personagem')),
            ],
        ),
        migrations.DeleteModel(
            name='Ataque',
        ),
    ]
