# Generated by Django 5.0.6 on 2025-07-10 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0002_combate_participante_turno_delete_ataque'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='ordem',
            field=models.PositiveIntegerField(),
        ),
    ]
