# Generated by Django 5.0.6 on 2025-07-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0003_turno_criado_em_alter_turno_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
