# Generated by Django 5.0.6 on 2025-07-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0004_turno_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='aflicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='dano',
            field=models.IntegerField(default=0),
        ),
    ]
