# Generated by Django 5.0.6 on 2025-07-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0005_participante_aflicao_participante_dano'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='bonus_temporario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='penalidade_temporaria',
            field=models.IntegerField(default=0),
        ),
    ]
