# Generated by Django 5.0.6 on 2025-08-04 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0006_participante_bonus_temporario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='mapas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas', to='combate.combate')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosicaoPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combate.mapa')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combate.participante')),
            ],
        ),
    ]
