# Generated by Django 5.0.6 on 2025-08-04 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0007_mapa_posicaopersonagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapa',
            name='combate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapas', to='combate.combate'),
        ),
    ]
