# Generated by Django 5.0.6 on 2025-08-05 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0008_alter_mapa_combate'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combate',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combates', to='salas.sala'),
        ),
    ]
