# Generated by Django 5.2.4 on 2025-09-02 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0009_combate_sala'),
        ('personagens', '0027_poder_duracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfeitoConcentracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('rodada_inicio', models.IntegerField(default=0)),
                ('alvo_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentracoes_recebidas', to='combate.participante')),
                ('aplicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentracoes_aplicadas', to='personagens.personagem')),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efeitos_concentracao', to='combate.combate')),
                ('poder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagens.poder')),
            ],
        ),
    ]
