# Generated by Django 5.2.4 on 2025-09-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0012_participante_proximo_bonus_por_atributo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='penalidade_salv_aflicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='penalidade_salv_dano',
            field=models.IntegerField(default=0),
        ),
    ]
