# Generated by Django 5.2.4 on 2025-09-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
