# Generated by Django 5.2.4 on 2025-11-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_alter_item_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mods',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
