# Generated by Django 5.2.4 on 2025-11-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0004_itempoder_and_unique_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
