# Generated by Django 5.2.5 on 2025-11-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0005_alter_item_unique_together_alter_item_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='raridade',
            field=models.CharField(blank=True, choices=[('artifact', 'Artifact'), ('legendary', 'Legendary'), ('very rare', 'Very Rare'), ('rare', 'Rare'), ('uncommon', 'Uncommon'), ('common', 'Common')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Armor', 'Armor'), ('Ring', 'Ring'), ('Wondrous Item', 'Wondrous Item'), ('Ranged Weapon', 'Ranged Weapon'), ('Melee Weapon', 'Melee Weapon'), ('Staff', 'Staff'), ('Wand', 'Wand'), ('Gear', 'Gear')], max_length=50),
        ),
    ]
