# Generated by Django 5.2.5 on 2025-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0006_alter_item_raridade_alter_item_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempoder',
            name='caminho_aflicao',
            field=models.CharField(blank=True, choices=[('fisico', 'Físico'), ('mental', 'Mental'), ('misto', 'Misto')], default='', max_length=20),
        ),
    ]
