# Generated by Django 5.2.5 on 2025-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0007_itempoder_caminho_aflicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempoder',
            name='caminho_aflicao',
            field=models.CharField(blank=True, choices=[('controle_mental', 'Controle mental/comportamento'), ('restricao_fisica', 'Restrição física/movimentação'), ('debilitacao', 'Debilitação/consciência')], default='', max_length=20),
        ),
    ]
