# Generated by Django 5.2.4 on 2025-12-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0008_alter_itempoder_caminho_aflicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempoder',
            name='tipo_dano',
            field=models.CharField(choices=[('fisico', 'Físico'), ('acido', 'Ácido'), ('gelo', 'Gelo'), ('fogo', 'Fogo'), ('raio', 'Raio'), ('veneno', 'Veneno'), ('mental', 'Mental'), ('trovao', 'Trovão'), ('necrotico', 'Necrótico'), ('radiante', 'Radiante')], default='fisico', max_length=20),
        ),
    ]
