# Generated by Django 5.2.9 on 2025-12-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0009_itempoder_tipo_dano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempoder',
            name='duracao',
            field=models.CharField(choices=[('instantaneo', 'Instantâneo'), ('concentracao', 'Concentração'), ('sustentado', 'Sustentado'), ('reacao', 'Reação')], default='instantaneo', max_length=20),
        ),
    ]
