# Generated by Django 5.0.6 on 2025-07-09 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel_poder', models.IntegerField(default=10)),
                ('forca', models.IntegerField(default=0)),
                ('destreza', models.IntegerField(default=0)),
                ('constituicao', models.IntegerField(default=0)),
                ('inteligencia', models.IntegerField(default=0)),
                ('sabedoria', models.IntegerField(default=0)),
                ('carisma', models.IntegerField(default=0)),
                ('esquiva', models.IntegerField(default=0)),
                ('fortitude', models.IntegerField(default=0)),
                ('resistencia', models.IntegerField(default=0)),
                ('vontade', models.IntegerField(default=0)),
                ('defesa', models.IntegerField(default=0)),
                ('parry', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
