# Generated by Django 5.0.6 on 2025-07-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='acrobacia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='atletismo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='blefar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='conhecimento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='diplomacia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='enganacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='furtividade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='historia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='intimidacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='intuicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='investigacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='luta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='observar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='oficio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='percepcao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='prestidigitacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='religiao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='sobrevivencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='tecnologia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='vontade_pericia',
            field=models.IntegerField(default=0),
        ),
    ]
