# Generated by Django 5.0.6 on 2025-07-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0002_personagem_acrobacia_personagem_atletismo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='acrobacia',
            new_name='acrobacias',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='blefar',
            new_name='agilidade',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='carisma',
            new_name='aparar',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='conhecimento',
            new_name='combate_corpo',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='constituicao',
            new_name='combate_distancia',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='defesa',
            new_name='especialidade',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='diplomacia',
            new_name='esquivar',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='esquiva',
            new_name='intelecto',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='inteligencia',
            new_name='persuasao',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='observar',
            new_name='presenca',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='oficio',
            new_name='prontidao',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='parry',
            new_name='tratamento',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='religiao',
            new_name='veiculos',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='sabedoria',
            new_name='vigor',
        ),
        migrations.RemoveField(
            model_name='personagem',
            name='vontade_pericia',
        ),
    ]
