# Generated by Django 5.0.6 on 2025-07-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0003_rename_acrobacia_personagem_acrobacias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='intelecto',
            new_name='inteligencia',
        ),
    ]
