# Generated by Django 5.0.6 on 2025-07-09 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0004_rename_intelecto_personagem_inteligencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bonus_ataque', models.IntegerField(default=0)),
                ('nivel_efeito', models.IntegerField(default=0)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poderes', to='personagens.personagem')),
            ],
        ),
    ]
