# Generated by Django 5.0.6 on 2025-07-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0005_poder'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='condicao',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='personagem',
            name='penalidade_resistencia',
            field=models.IntegerField(default=0),
        ),
    ]
