# Generated by Django 5.0.6 on 2025-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0006_personagem_condicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='penalidade_resistencia',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
