# Generated by Django 5.0.6 on 2025-07-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0007_alter_personagem_penalidade_resistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='poder',
            name='defesa_ativa',
            field=models.CharField(choices=[('esquiva', 'Esquiva'), ('aparar', 'Aparar')], default='aparar', max_length=20),
        ),
        migrations.AddField(
            model_name='poder',
            name='defesa_passiva',
            field=models.CharField(choices=[('fortitude', 'Fortitude'), ('resistencia', 'Resistência'), ('vontade', 'Vontade')], default='resistencia', max_length=20),
        ),
        migrations.AddField(
            model_name='poder',
            name='modo',
            field=models.CharField(choices=[('area', 'Área'), ('percepcao', 'Percepção'), ('ranged', 'À Distância'), ('melee', 'Corpo a Corpo')], default='melee', max_length=20),
        ),
        migrations.AddField(
            model_name='poder',
            name='tipo',
            field=models.CharField(choices=[('aflicao', 'Aflição'), ('dano', 'Dano'), ('cura', 'Cura'), ('buff', 'Buff'), ('debuff', 'Debuff')], default='dano', max_length=20),
        ),
    ]
