# Generated by Django 5.0.6 on 2025-07-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0008_poder_defesa_ativa_poder_defesa_passiva_poder_modo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poder',
            name='casting_ability',
            field=models.CharField(choices=[('forca', 'Força'), ('vigor', 'Vigor'), ('destreza', 'Destreza'), ('agilidade', 'Agilidade'), ('luta', 'Luta'), ('inteligencia', 'Inteligência'), ('prontidao', 'Prontidão'), ('presenca', 'Presença')], default='inteligencia', max_length=20, verbose_name='Habilidade de Conjuração'),
        ),
    ]
