# Generated by Django 5.0.6 on 2025-07-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0009_poder_casting_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='especialidade_casting_ability',
            field=models.CharField(choices=[('forca', 'Força'), ('vigor', 'Vigor'), ('destreza', 'Destreza'), ('agilidade', 'Agilidade'), ('luta', 'Luta'), ('inteligencia', 'Inteligência'), ('prontidao', 'Prontidão'), ('presenca', 'Presença')], default='inteligencia', max_length=20, verbose_name='Habilidade de Conjuração da Especialidade'),
        ),
    ]
