# Generated by Django 5.0.6 on 2025-08-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0010_personagem_especialidade_casting_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='personagens_fotos/'),
        ),
    ]
