# Generated by Django 5.0.6 on 2025-08-06 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0013_perfilusuario_sala_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.PositiveIntegerField(default=0)),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('raro', 'Raro'), ('epico', 'Épico'), ('lendario', 'Lendário')], default='comum', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouro', models.PositiveIntegerField(default=0)),
                ('dragon_shard', models.PositiveIntegerField(default=0)),
                ('personagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='personagens.personagem')),
                ('itens', models.ManyToManyField(blank=True, to='personagens.item')),
            ],
        ),
    ]
