# Generated by Django 5.0.6 on 2025-08-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0014_item_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='raridade',
            field=models.CharField(max_length=50),
        ),
    ]
