# Generated by Django 5.0.6 on 2025-08-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0015_item_tipo_alter_item_descricao_alter_item_raridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='raridade',
            field=models.CharField(blank=True, choices=[('artifact', 'Artifact'), ('common', 'Common'), ('legendary', 'Legendary'), ('none', 'Unknown'), ('rare', 'Rare'), ('uncommon', 'Uncommon'), ('unknown', 'Unknown'), ('unknown (magic)', 'Unknown (Magic)'), ('varies', 'Varies'), ('very rare', 'Very Rare')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Adventuring Gear', 'Adventuring Gear'), ('Air Vehicle', 'Air Vehicle'), ('Ammunition', 'Ammunition'), ("Artisan's Tools", "Artisan's Tools"), ('Explosive', 'Explosive'), ('Food/Drink', 'Food/Drink'), ('Gaming Set', 'Gaming Set'), ('Generic Variant', 'Generic Variant'), ('Heavy Armor', 'Heavy Armor'), ('Idol/Relic', 'Idol/Relic'), ('Instrument', 'Instrument'), ('Light Armor', 'Light Armor'), ('Medium Armor', 'Medium Armor'), ('Melee Weapon', 'Melee Weapon'), ('Mount', 'Mount'), ('Other', 'Other'), ('Poison', 'Poison'), ('Ranged Weapon', 'Ranged Weapon'), ('Ring', 'Ring'), ('Rod', 'Rod'), ('Scroll', 'Scroll'), ('Shield', 'Shield'), ('Ship', 'Ship'), ('Space Vehicle', 'Space Vehicle'), ('Spellcasting Focus', 'Spellcasting Focus'), ('Tack and Harness', 'Tack and Harness'), ('Tinker’s Tool (Bundle)', 'Tinker’s Tool (Bundle)'), ('Tool', 'Tool'), ('Trade Good', 'Trade Good'), ('Vehicle', 'Vehicle'), ('Wondrous Item', 'Wondrous Item'), ('martial Weapon, Melee Weapon', 'Martial Weapon, Melee Weapon'), ('martial Weapon, Ranged Weapon', 'Martial Weapon, Ranged Weapon'), ('simple Weapon, Melee Weapon', 'Simple Weapon, Melee Weapon'), ('simple Weapon, Ranged Weapon', 'Simple Weapon, Ranged Weapon')], max_length=50),
        ),
    ]
