# Generated by Django 5.0.6 on 2025-08-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0016_alter_item_raridade_alter_item_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
