# Generated by Django 5.0.6 on 2025-08-08 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0017_alter_item_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='poder',
            name='de_item',
            field=models.BooleanField(default=False, verbose_name='Poder de Item?'),
        ),
        migrations.AddField(
            model_name='poder',
            name='item_origem',
            field=models.ForeignKey(blank=True, help_text='Se for poder de item, selecione o item de origem.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personagens.item'),
        ),
    ]
