# Generated by Django 5.0.6 on 2025-08-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0018_poder_de_item_poder_item_origem'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='salas.sala'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('nome', 'sala')},
        ),
    ]
