# Generated by Django 5.0.6 on 2025-08-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
        ('personagens', '0019_item_sala_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poder',
            name='item_origem',
            field=models.ForeignKey(blank=True, help_text='Se for poder de item, selecione o item de origem.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.item'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='itens',
            field=models.ManyToManyField(blank=True, to='itens.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
