# Generated by Django 5.0.6 on 2025-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0020_alter_poder_item_origem_alter_inventario_itens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vantagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='personagem',
            name='vantagens',
            field=models.ManyToManyField(blank=True, to='personagens.vantagem'),
        ),
    ]
