# Generated by Django 5.0.6 on 2025-08-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0021_vantagem_personagem_vantagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='poder',
            name='de_vantagem',
            field=models.BooleanField(default=False, verbose_name='Poder de Vantagem?'),
        ),
        migrations.AddField(
            model_name='poder',
            name='vantagem_origem',
            field=models.ForeignKey(blank=True, help_text='Se for poder de vantagem, selecione a vantagem de origem.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personagens.vantagem'),
        ),
    ]
