# Generated by Django 5.2.4 on 2025-08-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0022_poder_de_vantagem_poder_vantagem_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='is_npc',
            field=models.BooleanField(default=False),
        ),
    ]
