# Generated by Django 5.2.4 on 2025-08-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0025_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poder',
            name='tipo',
            field=models.CharField(choices=[('descritivo', 'Descritivo'), ('aflicao', 'Aflição'), ('dano', 'Dano'), ('cura', 'Cura'), ('buff', 'Buff'), ('debuff', 'Debuff')], default='dano', max_length=20),
        ),
    ]
