# Generated by Django 5.2.4 on 2025-09-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0026_alter_poder_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poder',
            name='duracao',
            field=models.CharField(choices=[('instantaneo', 'Instantâneo'), ('concentracao', 'Concentração')], default='instantaneo', max_length=20),
        ),
    ]
