# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0027_poder_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poder',
            name='duracao',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('instantaneo', 'Instantâneo'),
                    ('concentracao', 'Concentração'),
                    ('sustentado', 'Sustentado'),
                ],
                default='instantaneo',
            ),
        ),
    ]
