# Generated by Django 5.2.5 on 2025-09-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0029_poder_ligados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poder',
            name='ligados',
            field=models.ManyToManyField(blank=True, help_text='Poderes que disparam em cadeia junto com este. Precisam ter mesmo modo e duração.', to='personagens.poder'),
        ),
    ]
