# Generated by Django 5.2.4 on 2025-09-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0033_merge_ligados_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='arcana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='religiao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poder',
            name='ligados',
            field=models.ManyToManyField(blank=True, help_text='Poderes que disparam em cadeia junto com este. Precisam ter mesmo nome, modo e duração.', to='personagens.poder'),
        ),
    ]
