# Generated by Django 5.2.4 on 2025-09-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0035_merge_debuff_into_buff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poder',
            name='tipo',
            field=models.CharField(choices=[('descritivo', 'Descritivo'), ('aflicao', 'Aflição'), ('dano', 'Dano'), ('cura', 'Cura'), ('buff', 'Buff/Debuff'), ('aprimorar', 'Aprimorar/Reduzir')], default='dano', max_length=20),
        ),
    ]
