# Generated by Django 5.2.4 on 2025-09-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0036_alter_poder_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poder',
            name='casting_ability',
            field=models.CharField(choices=[('forca', 'Força'), ('vigor', 'Vigor'), ('destreza', 'Destreza'), ('agilidade', 'Agilidade'), ('luta', 'Luta'), ('inteligencia', 'Inteligência'), ('prontidao', 'Prontidão'), ('presenca', 'Presença'), ('aparar', 'Aparar'), ('esquivar', 'Esquivar'), ('fortitude', 'Fortitude'), ('vontade', 'Vontade'), ('resistencia', 'Resistência')], default='inteligencia', max_length=20, verbose_name='Habilidade de Conjuração'),
        ),
    ]
