# Generated by Django 5.2.4 on 2025-09-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0038_alter_poder_casting_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poder',
            name='casting_ability',
            field=models.CharField(choices=[('forca', 'Força'), ('vigor', 'Vigor'), ('destreza', 'Destreza'), ('agilidade', 'Agilidade'), ('luta', 'Luta'), ('inteligencia', 'Inteligência'), ('prontidao', 'Prontidão'), ('presenca', 'Presença'), ('aparar', 'Aparar'), ('esquivar', 'Esquivar'), ('fortitude', 'Fortitude'), ('vontade', 'Vontade'), ('resistencia', 'Resistência')], default='inteligencia', help_text='Usado apenas por poderes Aprimorar/Reduzir', max_length=20, verbose_name='Atributo Afetado'),
        ),
    ]
