# Generated by Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0041_poder_somar_forca_no_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='poder',
            name='charges',
            field=models.PositiveIntegerField(blank=True, null=True, default=None, verbose_name='Charges'),
        ),
    ]
