# Generated by Django 5.2.4 on 2025-11-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
		('personagens', '0042_poder_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='poder',
            name='caminho_aflicao',
            field=models.CharField(blank=True, choices=[('mental', 'Controle mental/comportamento'), ('restricao', 'Restrição física/movimentação'), ('debilitacao', 'Debilitação/consciência')], default='mental', help_text='Define o caminho da Aflição: mental (Transe/Compelido/Controlado), restricao (Impedido/Imóvel/Incapacitado) ou debilitacao (Tonto/Atordoado/Paralizado).', max_length=20),
        ),
    ]
