# Generated by Django 5.2.4 on 2025-12-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0044_fill_caminho_aflicao_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='imunidades_dano',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='personagem',
            name='resistencias_dano',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='poder',
            name='tipo_dano',
            field=models.CharField(choices=[('fisico', 'Físico'), ('acido', 'Ácido'), ('gelo', 'Gelo'), ('fogo', 'Fogo'), ('raio', 'Raio'), ('veneno', 'Veneno'), ('mental', 'Mental'), ('trovao', 'Trovão'), ('necrotico', 'Necrótico'), ('radiante', 'Radiante')], default='fisico', help_text='Tipo de dano (apenas para poderes de Dano; Físico é o padrão).', max_length=20),
        ),
    ]
