# Generated by Django 5.2.9 on 2025-12-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0045_personagem_imunidades_dano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poder',
            name='duracao',
            field=models.CharField(choices=[('instantaneo', 'Instantâneo'), ('concentracao', 'Concentração'), ('sustentado', 'Sustentado'), ('reacao', 'Reação')], default='instantaneo', max_length=20),
        ),
    ]
