# Generated by Django 5.2.4 on 2025-12-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0046_alter_poder_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='campanga',
            field=models.BooleanField(default=False),
        ),
    ]
